import {Component, OnInit, SecurityContext} from '@angular/core';
import {Article} from "../../shared/api/Article";
import {ArticlesService} from "../../services/api/articles/articles.service";
import {DomSanitizer} from "@angular/platform-browser";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  private articles: Article[] = [];

  constructor(private articlesService: ArticlesService, private sanitizer: DomSanitizer) { }

  ngOnInit() {
    this.refresh();
  }

  private refresh() {
    this.articlesService.getAll().then(values => {
      this.articles = values;

      this.articles.forEach(value => {
        value.name = this.sanitizer.sanitize(SecurityContext.HTML, value.name);
        value.text = this.sanitizer.sanitize(SecurityContext.HTML, value.text);
      });
    }).catch(err => {
      console.error(err);
    })
  }

  private remove(id: string) {
    this.articlesService.delete(id).then( value => this.refresh() );
  }

  private add() {
    this.articlesService.create(new Article({
      name: "Generated " + Math.round(Math.random() * 1000),
      text: "autogenerated"
    })).then(value => this.refresh());
  }

}
